### ISSUE TITLE
Compil error on Travis CI using precise

### ISSUE THREAD

**Issue by ncornu** [CopernicaMarketingSoftware/PHP-CPP-LEGACY#5]
I try to build the PHP-CPP library on Travis CI precise and i get the following error:

```
In file included from /home/travis/.phpenv/versions/5.5.38/include/php/Zend/zend_alloc.h:27:0,

                 from /home/travis/.phpenv/versions/5.5.38/include/php/Zend/zend.h:252,

                 from /home/travis/.phpenv/versions/5.5.38/include/php/main/php.h:34,

                 from zend/includes.h:36,

                 from zend/value.cpp:27:

zend/value.cpp: In member function ‘bool Php::Value::isCallable(const char*)’:

zend/value.cpp:852:28: error: ‘tsrm_ls’ was not declared in this scope

     zend_class_entry *ce = Z_OBJCE_P(_val);

                            ^

make: *** [shared/zend/value.o] Error 1

The command "cd PHP-CPP-LEGACY-1.5.6 && make -j1 && make install" failed and exited with 2 during .
```

--------------------------------------------------------------------------------------
My travis.yml file is:
```
language: php
sudo: required
dist: trusty
addons:
 apt:
  packages:
   - php5-dev
before_script:
 - wget https://github.com/CopernicaMarketingSoftware/PHP-CPP-LEGACY/archive/v1.5.6.zip
 - unzip v1.5.6.zip
 - cd PHP-CPP-LEGACY-1.5.6 && make -j1 && make install
script: cmake . && make && make install
```
